services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "~/www/nginx:/www"
    depends_on:
      - php-fpm
    networks:
      - link
    restart: unless-stopped

  php-fpm:
    image: php:fpm-alpine
    container_name: php-fpm
    volumes:
      - "./php.ini:/usr/local/etc/php/php.ini"
      - "~/www/nginx:/www"
    networks:
      - link
    user: 1000:1000
    restart: unless-stopped

networks:
  link: